config/routes.rb
Rails.application.routes.draw do
  resources :linktypes
  resources :gamelinks
  resources :games
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    get 'useredit', to: 'devise/registrations#edit'
    
  end
  devise_for :user, controllers: {
        registrations: 'users/registrations'        
      }

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_error.html.slim
- if flash[:error].present? && flash[:error].is_a?(Array)
  .alert.alert-primary
    ul
      - flash[:error].each do |error|
        li 
          h4
            = error
- if flash[:notice].present?
  .alert.alert-primary
    = flash[:notice]

app/views/shared/_footer.html.slim
footer.pc-footer
    .footer-wrapper.container-fluid
      .row
        .col-1
          p.m-0
            = link_to "Discord", "https://discord.gg/uhADYMbD5j", target: "_blank"
        .col-1
          p.m-0
            = link_to "Facebook", "https://www.facebook.com/groups/2366748376888214", target: "_blank"
        
          
        .col-auto
          p.m-0
            =link_to "Home",  root_path
                
            
              
               
            

app/views/shared/_header.html.slim
header.pc-header
    .header-wrapper
      .me-auto.pc-mob-drp
        ul.list-unstyled
          li.pc-h-item.pc-sidebar-collapse
            a#sidebar-hide.pc-head-link.ms-0[href="#"]
              i.ph-duotone.ph-list
          li.pc-h-item.pc-sidebar-popup
            a#mobile-collapse.pc-head-link.ms-0[href="#"]
              i.ph-duotone.ph-list
          = search_form_for @q, url: games_path do |f|
            = f.text_field :name_cont, placeholder: "Gyors kereső...", class: "form-control mt-2", style: "width:230px !important; height:40px !important"

              
      .ms-auto
        ul.list-unstyled
          
            - if current_user
              /= render "shared/notification"
              = render "shared/profile"              
            - else
              = render "shared/login"

app/views/shared/_headerlocalmenu.html.slim
li.dropdown.pc-h-item
    a.pc-head-link.dropdown-toggle.arrow-none.me-0[data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false"]
        i.ph-duotone.ph-diamonds-four
    .dropdown-menu.dropdown-menu-end.pc-h-dropdown
        a.dropdown-item[href="#!"]
            i.ph-duotone.ph-user
            span
                | My Account
        a.dropdown-item[href="#!"]
            i.ph-duotone.ph-gear
            span
                | Settings
        a.dropdown-item[href="#!"]
            i.ph-duotone.ph-lifebuoy
            span
                | Support
        a.dropdown-item[href="#!"]
            i.ph-duotone.ph-lock-key
            span
                | Lock Screen
        a.dropdown-item[href="#!"]
            i.ph-duotone.ph-power
            span
                | Logout

app/views/shared/_headertheme.html.slim
li.dropdown.pc-h-item
    a.pc-head-link.dropdown-toggle.arrow-none.me-0[data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false"]
        i.ph-duotone.ph-sun-dim
    .dropdown-menu.dropdown-menu-end.pc-h-dropdown
        a.dropdown-item[href="#!" onclick="layout_change('dark')"]
            i.ph-duotone.ph-moon
            span
            | Sötét
        a.dropdown-item[href="#!" onclick="layout_change('light')"]
            i.ph-duotone.ph-sun-dim
            span
            | Világos
        

app/views/shared/_login.html.slim
li.dropdown.pc-h-item
    a.pc-head-link.dropdown-toggle.arrow-none.me-0[data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false"]
        i.ph-duotone.ph-sign-in
    .dropdown-menu.dropdown-menu-end.pc-h-dropdown
        - if current_user
            = link_to logout_path , class: "dropdown-item" do |link|
                i.ph-duotone.ph-sign-out
                span
                | Kilépés
        - else
            = link_to sign_in_path , class: "dropdown-item" do |link|
                i.ph-duotone.ph-sign-in
                span
                | Belépés
            = link_to new_user_registration_path , class: "dropdown-item" do |link|
                i.ph-duotone.ph-user-circle-plus
                span
                | Regisztráció
        

app/views/shared/_notification.html.slim
li.dropdown.pc-h-item
  a.pc-head-link.dropdown-toggle.arrow-none.me-0[data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false"]
    i.ph-duotone.ph-bell
    span.badge.bg-danger.pc-h-badge
      | 3
  .dropdown-menu.dropdown-notification.dropdown-menu-end.pc-h-dropdown
    .dropdown-header.d-flex.align-items-center.justify-content-between
      h4.m-0
        | Notifications
      ul.list-inline.ms-auto.mb-0
        li.list-inline-item
          a.avtar.avtar-s.btn-link-hover-primary[href="#"]
            i.ti.ti-arrows-diagonal.f-18
        li.list-inline-item
          a.avtar.avtar-s.btn-link-hover-danger[href="#"]
            i.ti.ti-x.f-18
    .dropdown-body.text-wrap.header-notification-scroll.position-relative[style="max-height: calc(100vh - 235px)"]
      ul.list-group.list-group-flush
        li.list-group-item
          p.text-span
            | Today
          .d-flex
            .flex-shrink-0
              = image_tag  "avatar-2.jpg", class: "user-avtar avtar avtar-s"
              
            .flex-grow-1.ms-3
              .d-flex
                .flex-grow-1.me-3.position-relative
                  h5.mb-0.text-truncate
                    | Keefe Bond 
                    span.text-body
                      |  added new tags to 
                    |  💪 Design system
                .flex-shrink-0
                  span.text-sm.text-muted
                    | 2 min ago
              p.position-relative.text-muted.mt-1.mb-2
                br
                span.text-truncate
                  | Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
              span.badge.bg-light-primary.border.border-primary.me-1.mt-1
                | web design
              span.badge.bg-light-warning.border.border-warning.me-1.mt-1
                | Dashobard
              span.badge.bg-light-success.border.border-success.me-1.mt-1
                | Design System
        li.list-group-item
          .d-flex
            .flex-shrink-0
              .avtar.avtar-s.bg-light-primary
                i.ph-duotone.ph-chats-teardrop.f-18
            .flex-grow-1.ms-3
              .d-flex
                .flex-grow-1.me-3.position-relative
                  h5.mb-0.text-truncate
                    | Message
                .flex-shrink-0
                  span.text-sm.text-muted
                    | 1 hour ago
              p.position-relative.text-muted.mt-1.mb-2
                br
                span.text-truncate
                  | Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
        li.list-group-item
          p.text-span
            | Yesterday
          .d-flex
            .flex-shrink-0
              .avtar.avtar-s.bg-light-danger
                i.ph-duotone.ph-user.f-18
            .flex-grow-1.ms-3
              .d-flex
                .flex-grow-1.me-3.position-relative
                  h5.mb-0.text-truncate
                    | Challenge invitation
                .flex-shrink-0
                  span.text-sm.text-muted
                    | 12 hour ago
              p.position-relative.text-muted.mt-1.mb-2
                br
                span.text-truncate
                  strong
                    |  Jonny aber 
                  |  invites to join the challenge
              button.btn.btn-sm.rounded-pill.btn-outline-secondary.me-2
                | Decline
              button.btn.btn-sm.rounded-pill.btn-primary
                | Accept
        li.list-group-item
          .d-flex
            .flex-shrink-0
              .avtar.avtar-s.bg-light-info
                i.ph-duotone.ph-notebook.f-18
            .flex-grow-1.ms-3
              .d-flex
                .flex-grow-1.me-3.position-relative
                  h5.mb-0.text-truncate
                    | Forms
                .flex-shrink-0
                  span.text-sm.text-muted
                    | 2 hour ago
              p.position-relative.text-muted.mt-1.mb-2
                | Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
        li.list-group-item
          .d-flex
            .flex-shrink-0
              = image_tag  "avatar-2.jpg", class: "user-avtar avtar avtar-s"
            .flex-grow-1.ms-3
              .d-flex
                .flex-grow-1.me-3.position-relative
                  h5.mb-0.text-truncate
                    | Keefe Bond 
                    span.text-body
                      |  added new tags to 
                    |  💪 Design system
                .flex-shrink-0
                  span.text-sm.text-muted
                    | 2 min ago
              p.position-relative.text-muted.mt-1.mb-2
                br
                span.text-truncate
                  | Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
              button.btn.btn-sm.rounded-pill.btn-outline-secondary.me-2
                | Decline
              button.btn.btn-sm.rounded-pill.btn-primary
                | Accept
        li.list-group-item
          .d-flex
            .flex-shrink-0
              .avtar.avtar-s.bg-light-success
                i.ph-duotone.ph-shield-checkered.f-18
            .flex-grow-1.ms-3
              .d-flex
                .flex-grow-1.me-3.position-relative
                  h5.mb-0.text-truncate
                    | Security
                .flex-shrink-0
                  span.text-sm.text-muted
                    | 5 hour ago
              p.position-relative.text-muted.mt-1.mb-2
                | Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
    .dropdown-footer
      .row.g-3
        .col-6
          .d-grid
            button.btn.btn-primary
              | Archive all
        .col-6
          .d-grid
            button.btn.btn-outline-secondary
              | Mark all as read

app/views/shared/_profile.html.slim
li.dropdown.pc-h-item.header-user-profile
  a.pc-head-link.dropdown-toggle.arrow-none.me-0[data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" data-bs-auto-close="outside" aria-expanded="false"]
    // = user_image_tag(current_user, "")
    
  .dropdown-menu.dropdown-user-profile.dropdown-menu-end.pc-h-dropdown
    .dropdown-header.d-flex.align-items-center.justify-content-between
      h4.m-0
        | Profil
      
    .dropdown-body
      .profile-notification-scroll.position-relative[style="max-height: calc(100vh - 225px)"]
        ul.list-group.list-group-flush.w-100
          li.list-group-item
            .d-flex.align-items-center
              .flex-shrink-0
                //= user_image_tag(current_user , "")
              .flex-grow-1.mx-3
                h5.mb-0
                  = current_user.username                   
                a.link-primary[href=""]
                  = current_user.email
              -if current_user.translater?
                span.badge.bg-danger
                  | Fordító
              -if current_user.admin?
                span.badge.bg-danger
                  | Admin
              
              
          li.list-group-item
            //=link_to pms_path, class: "dropdown-item" do |link|
              span.d-flex.align-items-center
                i.ph-duotone.ph-envelope-simple
                span
                  | Levelezés
            
          li.list-group-item
            .dropdown-item
              span.d-flex.align-items-center
                i.ph-duotone.ph-moon
                span
                  | Dark mód
              .form-check.form-switch.form-check-reverse.m-0
                input#dark-mode.form-check-input.f-18[type="checkbox" onclick="dark_mode()" role="switch"]
          li.list-group-item
            //= link_to settings_path , class: "dropdown-item" do
              span.d-flex.align-items-center
                i.ph-duotone.ph-user-circle
                span
                  | Beállítások
            
            a.dropdown-item[href="#"]
              span.d-flex.align-items-center
                i.ph-duotone.ph-bell
                span
                  | Értesítések
          
          li.list-group-item
            =link_to logout_path, class:"dropdown-item" do 
              span.d-flex.align-items-center
                i.ph-duotone.ph-power
                span
                  | Kilépés

app/views/shared/_sidebar.html.slim
nav.pc-sidebar
  .navbar-wrapper
    .m-header
      =link_to root_path , class: "b-brand.text-primary" do
        = image_tag("logo-white.svg", class: "logo-lg", width: "80%", alt: "logo image")

        span.badge.bg-danger.rounded-pill.ms-2.theme-version
          | v3.0
    .card.pc-user-card
      .card-body
        - if current_user
          .nav-user-image
            a[data-bs-toggle="collapse" href="#navuserlink"]
              //= user_image_tag(current_user, "user-avtar")
          #navuserlink.pc-user-collpsed.collapse
            h4.mb-0
              = current_user.username
            span
              -if current_user.translater?
                | Fordító
              -if current_user.admin?
                | Admin
            ul
              /*
                li
                  a.pc-user-links
                    i.ph-duotone.ph-user
                    span
                      | My Account
              
              li
                //=link_to settings_path, class: "pc-user-links" do
                  i.ph-duotone.ph-gear
                  span
                    | Beállítások
              /*
                li
                  a.pc-user-links
                    i.ph-duotone.ph-lock-key
                    span
                      | Lock Screen
              li
                = link_to logout_path, class:"pc-user-links" do
                  i.ph-duotone.ph-power
                  span
                    | Kilépés
        - else
          .nav-user-image
            = image_tag("logo-white-sm.svg", class: "user-avtar rounded", width: "100px;", alt: "logo image")

            
    .navbar-content
      ul.pc-navbar
        li.pc-item.pc-caption
          label
            | Infó
        li.pc-item.pc-hasmenu
          a.pc-link[href="#!"]
            span.pc-micon
              i.fas.fa-comments
            span.pc-mtext
              | Hozzászólások
            span.pc-arrow
              i[data-feather="chevron-right"]
          ul.pc-submenu style=""
          
            //- Gmessage.order(id: :DESC).first(10).each do |message|
              = link_to game_path(message.game_id) , class: "pc-link" do |link|
                  - gamename = Game.find(message.game_id).name
                  li.pc-item.p-2.border-start.border-secondary style=" width : 200px;" title="#{gamename.upcase}" 
                    .bg-secondary.text-black style=" width: 200px; "
                      b.m-2
                        = truncate(gamename.upcase, length:20, separator: "...")
                    br
                    - szoveg = truncate(message.desc.to_s, length: 300, separator: '...')
                    = ActionView::Base.full_sanitizer.sanitize(szoveg)
                    br
                    b
                      |   #{message.user.alias || message.user.name}
                    br                     
                    |(
                    |#{message.created_at.strftime("%Y-%m-%d %H:%M") }
                    |) 
        li.pc-item.pc-hasmenu
          a.pc-link[href="#!"]
            span.pc-micon
              i.fas.fa-comments
            span.pc-mtext
              | Disqus
            span.pc-arrow
              i[data-feather="chevron-right"]
          ul.pc-submenu
          
            //- @rss.each do |rss|
              = link_to rss.link , class: "pc-link" do |link|
                  - path = URI.parse(rss.link.html_safe).path
                  - pathname = Pathname.new(path)
                  li.pc-item.p-2.border-start.border-secondary style=" width : 200px;" title="#{pathname.basename.to_s.gsub("-"," ").upcase}"
                    .bg-secondary.text-black style=" width: 200px; "
                      b.m-2
                        = truncate(pathname.basename.to_s.gsub("-"," ").upcase, length:20, separator: "...")
                    br
                    - szoveg = truncate(strip_tags(rss.desc), length: 100, separator: '...')
                    = szoveg
                    br
                    b
                      |#{rss.user}
                    br

                    -parsed_date = DateTime.parse(rss.idouj3.to_s) 
                    |(
                    |#{parsed_date.strftime("%Y-%m-%d %H:%M") }
                    |) 
            
        li.pc-item.pc-hasmenu
          a.pc-link[href="#!"]
            span.pc-micon
              i.fas.fa-upload
            span.pc-mtext
              | Feltöltések
            span.pc-arrow
              i[data-feather="chevron-right"]
          ul.pc-submenu
          
            //-@uploading.each do |t|
              = link_to game_path(t.game), class: "pc-link" do |link|
                li.pc-item.p-2.border-start.border-secondary style=" width : 200px; "
                  .bg-secondary.text-black style=" width: 200px; "
                    b.m-2
                      =t.game.name
                  br
                  |(
                  =t.created_at.strftime("%Y-%m-%d %H:%M") 
                  |)
            
        li.pc-item.pc-hasmenu
          a.pc-link[href="#!"]
            span.pc-micon
              i.fas.fa-download
            span.pc-mtext
              | Letöltések
            span.pc-arrow
              i[data-feather="chevron-right"]
          ul.pc-submenu
          
            //-@download.each do |t|
              = link_to  game_path(t.game), class: "pc-link" do |link|
                li.pc-item.p-2.border-start.border-secondary style=" width : 200px; "
                  .bg-secondary.text-black style=" width: 200px; "
                    b.m-2
                      =t.game.name
                  br
                  |  (
                  = statisztika(t.game.id,t.id)
                  |.letöltés)
                  br 
                  |#
                  =t.upload.id
                  br
              
                  -if current_user&.admin?
                      -begin
                          - dimensions = t.game.image.blob.metadata
                          - arany =  (dimensions["width"].to_f / dimensions["height"].to_f )*16/9
                          - if arany < 3
                              .buzi.btn-success.btn   
                                  |Javítandó!!!!!
                              br
                          
                      -rescue
                          
                          
                  |(
                  =t.created_at.strftime("%Y-%m-%d %H:%M") 
                  |)             
        
      /      
        li.pc-item.pc-caption
          label
            | Other
          i.ph-duotone.ph-suitcase
          span
            | Extra More Things
        li.pc-item.pc-hasmenu
          a.pc-link[href="#!"]
            span.pc-micon
              i.ph-duotone.ph-tree-structure
            span.pc-mtext
              | Menu levels
            span.pc-arrow
              i[data-feather="chevron-right"]
          ul.pc-submenu
            li.pc-item
              a.pc-link[href="#!"]
                | Level 2.1
            li.pc-item.pc-hasmenu
              a.pc-link[href="#!"]
                | Level 2.2
                span.pc-arrow
                  i[data-feather="chevron-right"]
              ul.pc-submenu
                li.pc-item
                  a.pc-link[href="#!"]
                    | Level 3.1
                li.pc-item
                  a.pc-link[href="#!"]
                    | Level 3.2
                li.pc-item.pc-hasmenu
                  a.pc-link[href="#!"]
                    | Level 3.3
                    span.pc-arrow
                      i[data-feather="chevron-right"]
                  ul.pc-submenu
                    li.pc-item
                      a.pc-link[href="#!"]
                        | Level 4.1
                    li.pc-item
                      a.pc-link[href="#!"]
                        | Level 4.2
            li.pc-item.pc-hasmenu
              a.pc-link[href="#!"]
                |  Level 2.3
                span.pc-arrow
                  i[data-feather="chevron-right"]
              ul.pc-submenu
                li.pc-item
                  a.pc-link[href="#!"]
                    | Level 3.1
                li.pc-item
                  a.pc-link[href="#!"]
                    | Level 3.2
                li.pc-item.pc-hasmenu
                  a.pc-link[href="#!"]
                    |  Level 3.3
                    span.pc-arrow
                      i[data-feather="chevron-right"]
                  ul.pc-submenu
                    li.pc-item
                      a.pc-link[href="#!"]
                        | Level 4.1
                    li.pc-item
                      a.pc-link[href="#!"]
                        | Level 4.2
        /li.pc-item
          a.pc-link[href="../other/sample-page.html"]
            span.pc-micon
              i.ph-duotone.ph-desktop
            span.pc-mtext
              | Sample page
      /.card.nav-action-card
        .card-body
          |  Alsó kocka 