config/routes.rb
Rails.application.routes.draw do
  resources :linktypes
  resources :gamelinks
  resources :games
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    get 'useredit', to: 'devise/registrations#edit'
    
  end
  devise_for :user, controllers: {
        registrations: 'users/registrations'        
      }

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/gamelink.rb
class Gamelink < ApplicationRecord
  belongs_to :game
  belongs_to :linktype
end

app/controllers/gamelinks_controller.rb
class GamelinksController < ApplicationController
  before_action :set_gamelink, only: %i[ show edit update destroy ]

  # GET /gamelinks or /gamelinks.json
  def index
    @gamelinks = Gamelink.all
  end

  # GET /gamelinks/1 or /gamelinks/1.json
  def show
  end

  # GET /gamelinks/new
  def new
    @gamelink = Gamelink.new
  end

  # GET /gamelinks/1/edit
  def edit
  end

  # POST /gamelinks or /gamelinks.json
  def create
    @gamelink = Gamelink.new(gamelink_params)

    respond_to do |format|
      if @gamelink.save
        format.html { redirect_to gamelink_url(@gamelink), notice: "Gamelink was successfully created." }
        format.json { render :show, status: :created, location: @gamelink }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gamelink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gamelinks/1 or /gamelinks/1.json
  def update
    respond_to do |format|
      if @gamelink.update(gamelink_params)
        format.html { redirect_to gamelink_url(@gamelink), notice: "Gamelink was successfully updated." }
        format.json { render :show, status: :ok, location: @gamelink }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gamelink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamelinks/1 or /gamelinks/1.json
  def destroy
    @gamelink.destroy!

    respond_to do |format|
      format.html { redirect_to gamelinks_url, notice: "Gamelink was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamelink
      @gamelink = Gamelink.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gamelink_params
      params.require(:gamelink).permit(:game_id, :link, :linktype_id)
    end
end

app/helpers/gamelinks_helper.rb
module GamelinksHelper
end

app/views/gamelinks/_form.html.slim
= simple_form_for(@gamelink) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :game
    = f.input :link
    = f.association :linktype

  .form-actions
    = f.button :submit

app/views/gamelinks/_gamelink.html.slim
div id="#{dom_id gamelink}"
  p
    strong Game:
    =< gamelink.game_id
  p
    strong Link:
    =< gamelink.link
  p
    strong Linktype:
    =< gamelink.linktype_id

app/views/gamelinks/edit.html.slim
h1 Editing gamelink

== render "form", gamelink: @gamelink

br

div
  => link_to "Show this gamelink", @gamelink
  '|
  =< link_to "Back to gamelinks", gamelinks_path

app/views/gamelinks/index.html.slim
p style="color: green" = notice

h1 Gamelinks

#gamelinks
  - @gamelinks.each do |gamelink|
    == render gamelink
    p
      = link_to "Show this gamelink", gamelink

= link_to "New gamelink", new_gamelink_path

app/views/gamelinks/new.html.slim
h1 New gamelink

== render "form", gamelink: @gamelink

br

div
  = link_to "Back to gamelinks", gamelinks_path

app/views/gamelinks/show.html.slim
p style="color: green" = notice

== render @gamelink

div
  => link_to "Edit this gamelink", edit_gamelink_path(@gamelink)
  '|
  =< link_to "Back to gamelinks", gamelinks_path

  = button_to "Destroy this gamelink", @gamelink, method: :delete