config/routes.rb
Rails.application.routes.draw do
  resources :linktypes
  resources :gamelinks
  resources :games
  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    get 'useredit', to: 'devise/registrations#edit'
    
  end
  devise_for :user, controllers: {
        registrations: 'users/registrations'        
      }

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/linktypes_controller.rb
class LinktypesController < ApplicationController
  before_action :set_linktype, only: %i[ show edit update destroy ]

  # GET /linktypes or /linktypes.json
  def index
    @linktypes = Linktype.all
  end

  # GET /linktypes/1 or /linktypes/1.json
  def show
  end

  # GET /linktypes/new
  def new
    @linktype = Linktype.new
  end

  # GET /linktypes/1/edit
  def edit
  end

  # POST /linktypes or /linktypes.json
  def create
    @linktype = Linktype.new(linktype_params)

    respond_to do |format|
      if @linktype.save
        format.html { redirect_to linktype_url(@linktype), notice: "Linktype was successfully created." }
        format.json { render :show, status: :created, location: @linktype }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @linktype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linktypes/1 or /linktypes/1.json
  def update
    respond_to do |format|
      if @linktype.update(linktype_params)
        format.html { redirect_to linktype_url(@linktype), notice: "Linktype was successfully updated." }
        format.json { render :show, status: :ok, location: @linktype }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @linktype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linktypes/1 or /linktypes/1.json
  def destroy
    @linktype.destroy!

    respond_to do |format|
      format.html { redirect_to linktypes_url, notice: "Linktype was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linktype
      @linktype = Linktype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def linktype_params
      params.require(:linktype).permit(:name, :icon)
    end
end

app/helpers/linktypes_helper.rb
module LinktypesHelper
end

app/views/linktypes/_form.html.slim
= simple_form_for(@linktype) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :icon

  .form-actions
    = f.button :submit

app/views/linktypes/_linktype.html.slim
div id="#{dom_id linktype}"
  p
    strong Name:
    =< linktype.name
  p
    strong IkonKód:
    =< linktype.icon
  p
    strong Icon:
    =< linktype.icon.html_safe

app/views/linktypes/edit.html.slim
h1 Editing linktype

== render "form", linktype: @linktype

br

div
  => link_to "Show this linktype", @linktype
  '|
  =< link_to "Back to linktypes", linktypes_path

app/views/linktypes/index.html.slim
p style="color: green" = notice

h1 Linktypes

#linktypes
  - @linktypes.each do |linktype|
    == render linktype
    p
      = link_to "Show this linktype", linktype

= link_to "New linktype", new_linktype_path

app/views/linktypes/new.html.slim
h1 New linktype

== render "form", linktype: @linktype

br

div
  = link_to "Back to linktypes", linktypes_path

app/views/linktypes/show.html.slim
p style="color: green" = notice

== render @linktype

div
  => link_to "Edit this linktype", edit_linktype_path(@linktype)
  '|
  =< link_to "Back to linktypes", linktypes_path

  = button_to "Destroy this linktype", @linktype, method: :delete